In [7]:
# 구간 분할

import pandas as pd
import numpy as np

df = pd.read_csv('./data/auto-mpg.csv', header=None)
df.columns = [
    "mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model year", "origin", "name"
]

df['horsepower'] = df['horsepower'].replace('?', np.nan)
df = df.dropna(subset=['horsepower'], axis=0)
df['horsepower'] = df['horsepower'].astype('float')

count, bin_dividers = np.histogram(df["horsepower"], bins=3)

print(bin_dividers)
print(count)

[ 46.         107.33333333 168.66666667 230.        ]
[257 103  32]

In [9]:
bins_name = ['저출력', '보통출력', '고출력']
df['hp_bin'] = pd.cut(
    x=df['horsepower'],
    bins=bin_dividers,
    labels=bins_name,
    include_lowest=True
)

df[['horsepower', 'hp_bin']].head(10)

   horsepower hp_bin
0       130.0   보통출력
1       165.0   보통출력
2       150.0   보통출력
3       150.0   보통출력
4       140.0   보통출력
5       198.0    고출력
6       220.0    고출력
7       215.0    고출력
8       225.0    고출력
9       190.0    고출력

In [10]:
# 더미변수 (원-핫 인코딩)

hp_dummies = pd.get_dummies(df['hp_bin'])
hp_dummies.head(10)

     저출력   보통출력    고출력
0  False   True  False
1  False   True  False
2  False   True  False
3  False   True  False
4  False   True  False
5  False  False   True
6  False  False   True
7  False  False   True
8  False  False   True
9  False  False   True

In [11]:
hp_dummies = pd.get_dummies(df['hp_bin'], dtype=float)
hp_dummies.head(10)

   저출력  보통출력  고출력
0  0.0   1.0  0.0
1  0.0   1.0  0.0
2  0.0   1.0  0.0
3  0.0   1.0  0.0
4  0.0   1.0  0.0
5  0.0   0.0  1.0
6  0.0   0.0  1.0
7  0.0   0.0  1.0
8  0.0   0.0  1.0
9  0.0   0.0  1.0

In [ ]:
hp_dummies = pd.get_dummies(df['hp_bin'], dtype=int, drop_first=True)   # 다중 공선성 방지
hp_dummies.head(10)

   보통출력  고출력
0     1    0
1     1    0
2     1    0
3     1    0
4     1    0
5     0    1
6     0    1
7     0    1
8     0    1
9     0    1

In [22]:
# 레이블 인코딩

from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

onehot_labeled = label_encoder.fit_transform(df['hp_bin'])
# print(onehot_labeled)
# print(type(onehot_labeled))

onehot_reshaped = onehot_labeled.reshape(len(onehot_labeled), 1)    # reshape(-1, 1)
# print(onehot_reshaped)
# print(type(onehot_reshaped))

onehot_fitted = onehot_encoder.fit_transform(onehot_reshaped)
# print(onehot_fitted)
# print(type(onehot_fitted))

In [23]:
##