In [1]:
# csv 파일로 저장

import pandas as pd

data = {
    "name" : ["Jerry", "Riah", "Paul"],
    "algol" : ["A", "A+", "B"],
    "basic" : ["C", "B", "B+"],
    "c++" : ["B+", "C", "C+"]
}

df = pd.DataFrame(data)
df = df.set_index("name")
df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [2]:
df.to_csv("./data/df_sample2.csv")

In [3]:
df.to_csv("./data/df_sample_no_index2.csv", index=False)

In [4]:
# json 파일로 저장

import pandas as pd

data = {
    "name" : ["Jerry", "Riah", "Paul"],
    "algol" : ["A", "A+", "B"],
    "basic" : ["C", "B", "B+"],
    "c++" : ["B+", "C", "C+"]
}

df = pd.DataFrame(data)
df = df.set_index("name")
df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [5]:
df.to_json("./data/df_sample2.json")

In [6]:
df.to_json("./data/df_sample_split2.json", orient="split")

In [7]:
df.to_json("./data/df_sample_index2.json", orient="index")

In [8]:
df.to_json("./data/to_sample_columns2.json", orient="columns")

In [9]:
df.to_json("./data/df_sample_values2.json", orient="values")

In [11]:
# 여러개의 데이터프레임을 하나의 엑셀파일로 저장